# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'


fos_ck_editor:
    input_sync: true
    default_config: main_toolbar
    configs:
        main_toolbar:
            toolbar: "main_toolbar"
            stylesSet: "main_styles"
            fileBrowserRoute: elfinder
            fileBrowserRouteParameters: 
    toolbars:
        configs:
            main_toolbar:
                - { name: 'clipboard', items: [ 'Undo', 'Redo', '-' ] }
                - { name: 'paragraph', items: [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'] }
                - { name: 'links', items: [ 'Link', 'Unlink', 'Anchor' ] }
                - { name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'Smiley' ] }
                - { name: 'basicstyles', items: [ 'CopyFormatting', 'RemoveFormat' ] }
                - '/'
                - { name: 'styles', items: [ 'Styles', 'Format', 'FontSize' ] }
                - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', '-', ] }
                - { name: 'colors', items: [ 'TextColor', 'BGColor' ] }
                - { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] }
                - '/'
            fileBrowserRoute: 
                - elfinder
            fileBrowserRouteParameters: 
                

    styles:
        main_styles:
            - { name: "SEO : Très Important", element: "strong", attributes: { class: "seo_strong_tag" }}
            - { name: "SEO : Important", element: "em", attributes: { class: "seo_em_tag" }}


